INSTANCE_CONFIG_PATH = 'INST_CONFIG_PATH'
INSTANCE_SECRETS_PATH = 'INST_SECRETS_PATH'
INSTANCE_SECRETS_PARTAGES_PATH = 'INST_SECRETS_PARTAGES_PATH'
INSTANCE_NGINX_PATH = 'INST_NGINX_PATH'
PARAM_INSTANCE_CA_PATH = 'INST_CA_PATH'
PARAM_INSTANCE_CERT_PATH = 'INST_CERT_PATH'
PARAM_INSTANCE_ID_PATH = 'INST_ID_PATH'
PARAM_INSTANCE_KEY_PATH = 'INST_KEY_PATH'
PARAM_INSTANCE_IDMG_PATH = 'INST_IDMG_PATH'
PARAM_INSTANCE_SECURITE_PATH = 'INST_SECURITE_PATH'
PARAM_INSTANCE_CERTISSUER_URL = 'CERTISSUER_URL'
PARAM_INSTANCE_PASSWD_MQ_PATH = 'INST_PASSWD_MQ_PATH'
PARAM_INSTANCE_MQ_HOST = 'MQ_HOST'
PARAM_INSTANCE_MQ_PORT = 'MQ_PORT'

WEB_APP_PATH = 'WEB_APP_PATH'

ENV_WEB_CERT_PEM = 'WEB_CERT_PEM'
ENV_WEB_KEY_PEM = 'WEB_KEY_PEM'
ENV_WEB_PORT = 'WEB_PORT'

DOCKER_CONFIG_INSTANCE_ID = 'instance.id'
DOCKER_CONFIG_INSTANCE_SECURITE = 'instance.securite'
DOCKER_CONFIG_INSTANCE_IDMG = 'instance.idmg'

DOCKER_CONFIG_PKI_MILLEGRILLE = 'pki.millegrille'

PARAM_INSTANCE_ID = 'INSTANCE_ID'

CERTISSUER_PATH = 'CERTISSUER_PATH'

# Commandes supportees par l'instance (MQ)
REQUETE_CONFIGURATION_ACME = 'configurationAcme'
REQUETE_GET_PASSWORDS = 'getPasswords'
COMMANDE_TRANSMETTRE_CATALOGUES = 'transmettreCatalogues'
COMMANDE_CONFIGURER_DOMAINE = 'configurerDomaine'
COMMANDE_SET_HOSTNAME = 'setHostname'
COMMANDE_APPLICATION_INSTALLER = 'installerApplication'
COMMANDE_APPLICATION_SUPPRIMER = 'supprimerApplication'
COMMANDE_APPLICATION_ARRETER = 'arreterApplication'
COMMANDE_APPLICATION_DEMARRER = 'demarrerApplication'
COMMANDE_APPLICATION_REQUETE_CONFIG = 'requeteConfigurationApplication'
COMMANDE_APPLICATION_CONFIGURER = 'configurerApplication'
COMMANDE_SIGNER_CSR = 'signerCsr'
COMMANDE_SIGNER_COMPTE_USAGER = 'signerCompteUsager'
COMMANDE_SIGNER_PUBLICKEY_DOMAINE = 'signerPublickeyDomaine'
EVENEMENT_TOPOLOGIE_FICHEPUBLIQUE = 'fichePublique'
EVENEMENT_TOPOLOGIE_MODIFICATION_CONSIGNATION = 'modificationConsignation'

EVENEMENT_PRESENCE_INSTANCE = 'presence'

CONFIG_NOMFICHIER_ACME = 'acme.json'
CONFIG_NOMFICHIER_CONFIGURATION = 'config.json'
CONFIG_NOMFICHIER_CONFIGURATION_WEB_APPLICATIONS = 'web_applications.json'

INTERVALLE_VERIFIER_CERTIFICATS = 3600

FICHIER_ARCHIVES_APP = '/var/opt/millegrilles/configuration/archives.json'


