include:
  - ../include/base.yml
  - ../include/nginx.yml

configs:
  pki.web:
    file: ${MILLEGRILLES_ROOT}/secrets/webcert.pem # TODO
  pki.nginx:
    file: ${MILLEGRILLES_ROOT}/secrets/nginx.cert.pem # TODO
  pki.millegrille:
    file: ${MILLEGRILLES_ROOT}/secrets/millegrille.cert.pem # TODO

secrets:
  pki.web:
    file: ${MILLEGRILLES_ROOT}/secrets/webkey.pem
  pki.nginx:
    file: ${MILLEGRILLES_ROOT}/secrets/nginx.key.pem
