services:
  certissuer:
    image: registry.millegrilles.com/millegrilles/midcompte_python:2025.4.112
    user: "${CONTAINER_UID}:${CONTAINER_GID}"
    command: ["-m", "millegrilles_certissuer"]
    environment:
      - INSTANCE_ID=${INSTANCE_ID}
      - WEB_PORT=2080
    volumes:
      - ${MILLEGRILLES_ROOT}/etc:/var/opt/millegrilles/configuration:ro
      - ${MILLEGRILLES_ROOT}/etc/secrets/certissuer:/var/opt/millegrilles/certissuer
    networks:
      - app_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
