include:
  - ../include/base.yml
  - ../include/nginxinstall.yml
  - ../include/certissuer.yml

configs:
  pki.web:
    file: ${MILLEGRILLES_ROOT}/secrets/webcert.pem

secrets:
  pki.web:
    file: ${MILLEGRILLES_ROOT}/secrets/webkey.pem
