services:
  nginx:
    image: registry.millegrilles.com/millegrilles/nginx:1.31.0.null.2
    environment:
      - ONIONSERVICE_NAME=nginx
      - ONIONSERVICE_PORT=443
    volumes:
      - ${NGINX_PATH}/data:/var/opt/millegrilles/nginx/data:ro
      - ${NGINX_PATH}/modules:/etc/nginx/conf.d/modules:ro
      - ${NGINX_PATH}/html:/usr/share/nginx/html:ro
    networks:
      - millegrille_net
    ports:
      - "443:443"
      - "444:444"
      - "80:80"
      - "1443:1443"
      - "1444:1444"
      - "1445:1445"
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.nginx == true
      resources:
        limits:
          cpus: '2.0'
          memory: 30M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki.web
        target: /run/secrets/webcert.pem
      - source: pki.nginx
        target: /run/secrets/nginx.cert.pem
      - source: pki.millegrille
        target: /usr/share/nginx/files/certs/millegrille.cert.pem
    secrets:
      - source: pki.web
        target: webkey.pem
      - source: pki.nginx
        target: nginx.key.pem

  certissuer:
    image: registry.millegrilles.com/millegrilles/midcompte_python:2025.4.112
    command: ["-m", "millegrilles_certissuer"]
    environment:
      - WEB_PORT=2080
    volumes:
      - ${MILLEGRILLES_PATH}:/var/opt/millegrilles
    networks:
      - millegrille_net
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.certissuer == true
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000

  redis:
    image: registry.millegrilles.com:5000/millegrilles/redis:8.6.2-alpine.master.9
    hostname: redis
    volumes:
      - mg-redis:/data
    networks:
      - millegrille_net
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.redis == true
      resources:
        limits:
          cpus: '1.5'
          memory: 500M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki.redis
        target: /run/secrets/cert.pem
      - source: pki.millegrille
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: pki.redis
        target: key.pem
      - source: passwd.redis
        target: passwd.redis.txt

  mq:
    image: registry.millegrilles.com:5000/millegrilles/rabbitmq:4.2.5-management-alpine.master.13
    hostname: mq
    environment:
      - MG_KEY=/run/secrets/key.pem
      - WEB_KEY=/run/secrets/webkey.pem
      - CONFIG_FILE=/opt/rabbitmq/dist/config/rabbitmq.config
      - NODENAME=rabbit@mq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - millegrille_net
      - bridge
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.mq == true
      resources:
        limits:
          cpus: '3.0'
          memory: 2100M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki.millegrille
        target: /opt/rabbitmq/dist/certs/calist.cert.pem
      - source: pki.mq
        target: /opt/rabbitmq/dist/certs/cert.pem
      - source: pki.mq
        target: /opt/rabbitmq/dist/certs/webcert.pem
    secrets:
      - source: pki.mq
        target: key.pem
      - source: pki.mq
        target: webkey.pem

  mongo:
    image: mongo:8.2.6
    hostname: mongo
    command: ["mongod", "--tlsMode", "requireTLS", "--tlsCertificateKeyFile", "/run/secrets/mongo.key_cert.pem", "--tlsCAFile", "/run/secrets/millegrille.cert.pem", "--replSet", "rs0", "--clusterAuthMode", "x509", "--tlsClusterFile", "/run/secrets/mongo.key_cert.pem"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo.root.password
    volumes:
      - mongo-data:/data/db
    networks:
      - millegrille_net
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.database == true
      resources:
        limits:
          cpus: '3.0'
          memory: 2000M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki.mongo
        target: /run/secrets/mongo.cert.pem
      - source: pki.millegrille
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: pki.mongo
        target: mongo.key_cert.pem
      - source: pki.millegrille
        target: millegrille.cert.pem
      - source: passwd.mongo
        target: mongo.root.password

  midcompte:
    image: registry.millegrilles.com/millegrilles/midcompte_python:2025.4.112
    environment:
      - WEB_PORT=2444
    depends_on:
      - redis
      - mq
      - mongo
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.midcompte == true
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki.millegrille
        target: /run/secrets/pki.millegrille.cert
      - source: pki.midcompte
        target: /run/secrets/cert.pem
    secrets:
      - source: pki.midcompte
        target: key.pem
      - source: passwd.mongo
        target: passwd.mongo.txt
      - source: passwd.mqadmin
        target: passwd.mqadmin.txt
    ports:
      - "2444:2444"
    networks:
      - millegrille_net

  ceduleur:
    image: registry.millegrilles.com/millegrilles/midcompte_python:2025.4.112
    command: ["-m", "millegrilles_ceduleur"]
    environment:
      - CA_PATH=/run/secrets/pki.millegrille.cert
      - CERT_PATH=/run/secrets/cert.pem
      - KEY_PATH=/run/secrets/key.pem
      - MQ_HOSTNAME=mq
      - MQ_PORT=${MQ_PORT}
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mq
      - mongo
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.ceduleur == true
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki.millegrille
        target: /run/secrets/pki.millegrille.cert
      - source: pki.ceduleur
        target: /run/secrets/cert.pem
    secrets:
      - source: pki.ceduleur
        target: key.pem
    networks:
      - millegrille_net

  core:
    image: registry.millegrilles.com/millegrilles/core_rust:2026.0.119
    environment:
      - MG_MQ_HOST=mq
      - MG_MQ_PORT=5673
      - MG_MONGO_HOST=mongo
      - MG_MQ_SSL=on
      - MG_MQ_AUTH_CERT=on
      - CERTFILE=/run/secrets/cert.pem
      - KEYFILE=/run/secrets/key.pem
      - CAFILE=/run/secrets/millegrille.cert.pem
      - MG_FICHIERS_URL=https://fichiers:443
      - MG_REDIS_URL=rediss://client_rust@redis:6379#insecure
      - MG_REDIS_PASSWORD_FILE=/run/secrets/passwd.redis.txt
      - RUST_LOG=warn
      - MG_CERTISSUER_URL=http://certissuer:2080
    depends_on:
      - redis
      - mq
      - mongo
    volumes:
      - ${CONFIGURATION_PATH}:/var/opt/millegrilles/configuration:ro
      - millegrilles-domain-archives:/var/opt/millegrilles/archives
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.core == true
          - node.labels.millegrilles.database == true
      resources:
        limits:
          cpus: '2.0'
          memory: 200M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki.core
        target: /run/secrets/cert.pem
      - source: pki.millegrille
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: pki.core
        target: key.pem
      - source: passwd.redis
        target: passwd.redis.txt
    networks:
      - millegrille_net

  webauth:
    image: registry.millegrilles.com/millegrilles/webauth_python:2025.4.18
    environment:
      - MQ_HOSTNAME=${MQ_HOSTNAME}
      - MQ_PORT=${MQ_PORT}
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD_PATH=/run/secrets/passwd.redis.txt
      - CERT_PATH=/run/secrets/cert.pem
      - KEY_PATH=/run/secrets/key.pem
      - CA_PATH=/run/secrets/millegrille.cert.pem
      - WEB_PORT=1443
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.webauth == true
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 100
    configs:
      - source: pki.webauth
        target: /run/secrets/cert.pem
      - source: pki.millegrille
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: pki.webauth
        target: key.pem
      - source: pki.millegrille
        target: millegrille.cert.pem
    networks:
      - millegrille_net
      - bridge

  protected_webapi:
    image: registry.millegrilles.com/millegrilles/web_python:2025.4.58
    command: ["-m", "millegrilles_web"]
    environment:
      - MQ_HOSTNAME=mq
      - MQ_PORT=${MQ_PORT}
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD_PATH=/run/secrets/passwd.redis.txt
      - CERT_PATH=/run/secrets/cert.pem
      - KEY_PATH=/run/secrets/key.pem
      - CA_PATH=/run/secrets/millegrille.cert.pem
      - WEB_PORT=1443
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.web == true
      resources:
        limits:
          cpus: '2.0'
          memory: 150M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    configs:
      - source: pki.protected_webapi
        target: /run/secrets/cert.pem
      - source: pki.protected_webapi
        target: /run/secrets/webcert.pem
      - source: pki.millegrille
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: pki.protected_webapi
        target: key.pem
      - source: pki.protected_webapi
        target: webkey.pem
      - source: passwd.redis
        target: passwd.redis.txt
    networks:
      - millegrille_net

networks:
  millegrille_net:
    external: true

volumes:
  mg-redis:
  rabbitmq-data:
  mongo-data:

configs:
  pki.web:
    file: ${MILLEGRILLES_ROOT}/secrets/webcert.pem # TODO
  pki.nginx:
    file: ${MILLEGRILLES_ROOT}/secrets/nginx.cert.pem # TODO
  pki.millegrille:
    file: ${MILLEGRILLES_ROOT}/secrets/millegrille.cert.pem # TODO
  pki.redis:
    file: ${MILLEGRILLES_ROOT}/secrets/cert.pem # TODO
  pki.mq:
    file: ${MILLEGRILLES_ROOT}/secrets/cert.pem # TODO
  pki.mongo:
    file: ${MILLEGRILLES_ROOT}/secrets/mongo.cert.pem # TODO
  pki.midcompte:
    file: ${MILLEGRILLES_ROOT}/secrets/cert.pem # TODO
  pki.ceduleur:
    file: ${MILLEGRILLES_ROOT}/secrets/cert.pem # TODO
  pki.core:
    file: ${MILLEGRILLES_ROOT}/secrets/cert.pem # TODO
  pki.webauth:
    file: ${MILLEGRILLES_ROOT}/secrets/cert.pem # TODO
  pki.protected_webapi:
    file: ${MILLEGRILLES_ROOT}/secrets/cert.pem # TODO # and webcert.pem...

secrets:
  pki.web:
    file: ${MILLEGRILLES_ROOT}/secrets/webkey.pem
  pki.nginx:
    file: ${MILLEGRILLES_ROOT}/secrets/nginx.key.pem
  pki.redis:
    file: ${MILLEGRILLES_ROOT}/secrets/key.pem # TODO
  pki.mq:
    file: ${MILLEGRILLES_ROOT}/secrets/key.pem # TODO
  pki.mq_web:
    file: ${MILLEGRILLES_ROOT}/secrets/webkey.pem # TODO
  pki.mongo:
    file: ${MILLEGRILLES_ROOT}/secrets/mongo.key_cert.pem # TODO
  pki.millegrille:
    file: ${MILLEGRILLES_ROOT}/secrets/millegrille.cert.pem # TODO
  pki.midcompte:
    file: ${MILLEGRILLES_ROOT}/secrets/key.pem # TODO
  pki.ceduleur:
    file: ${MILLEGRILLES_ROOT}/secrets/key.pem # TODO
  pki.core:
    file: ${MILLEGRILLES_ROOT}/secrets/key.pem # TODO
  pki.webauth:
    file: ${MILLEGRILLES_ROOT}/secrets/key.pem # TODO
  pki.protected_webapi:
    file: ${MILLEGRILLES_ROOT}/secrets/key.pem # TODO
  pki.protected_webapi_web:
    file: ${MILLEGRILLES_ROOT}/secrets/webkey.pem # TODO
  passwd.redis:
    file: ${MILLEGRILLES_ROOT}/secrets/passwd.redis.txt # TODO
  passwd.mongo:
    file: ${MILLEGRILLES_ROOT}/secrets/passwd.mongo.txt # TODO
  passwd.mqadmin:
    file: ${MILLEGRILLES_ROOT}/secrets/passwd.mqadmin.txt # TODO
