management.ssl.port       = 8443
management.ssl.cacertfile = /run/secrets/millegrille.pem
management.ssl.certfile   = /run/secrets/cert.pem
management.ssl.keyfile    = /run/secrets/key.pem
management.ssl.versions.1 = tlsv1.3
management.ssl.versions.2 = tlsv1.2

management.path_prefix = /rabbitmq/