services:
  nginxinstall:
    image: registry.millegrilles.com/millegrilles/nginx:1.31.0.null.2
    volumes:
      - ${MILLEGRILLES_ROOT}/nginx/modules:/etc/nginx/conf.d/modules:ro
      - ${MILLEGRILLES_ROOT}/nginx/html:/usr/share/nginx/html:ro
    networks:
      - app_net
    ports:
      - "443:443"
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 30M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki_web
        target: /run/secrets/webcert.pem
    secrets:
      - source: pki_web
        target: webkey.pem

configs:
  pki_web:
    file: ${MILLEGRILLES_ROOT}/etc/secrets/pki.web.cert

secrets:
  pki_web:
    file: ${MILLEGRILLES_ROOT}/etc/secrets/pki.web.key
