services:
  protected_webapi:
    image: registry.millegrilles.com/millegrilles/web_python:2025.4.58
    command: ["-m", "millegrilles_web"]
    environment:
      - MQ_HOSTNAME=mq
      - MQ_PORT=${MQ_PORT}
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD_PATH=/run/secrets/passwd.redis.txt
      - CERT_PATH=/run/secrets/cert.pem
      - KEY_PATH=/run/secrets/key.pem
      - CA_PATH=/run/secrets/millegrille.cert.pem
      - WEB_PORT=1443
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.web == true
      resources:
        limits:
          cpus: '2.0'
          memory: 150M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    configs:
      - source: pki.protected_webapi
        target: /run/secrets/cert.pem
      - source: pki.protected_webapi
        target: /run/secrets/webcert.pem
      - source: pki.millegrille
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: pki.protected_webapi
        target: key.pem
      - source: pki.protected_webapi
        target: webkey.pem
      - source: passwd.redis
        target: passwd.redis.txt
    networks:
      - app_net
