services:
  redis:
    image: registry.millegrilles.com:5000/millegrilles/redis:8.6.2-alpine.master.9
    hostname: redis
    volumes:
      - mg-redis:/data
    networks:
      - ${INSTANCE_NAME}_net
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.redis == true
      resources:
        limits:
          cpus: '1.5'
          memory: 500M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki.redis
        target: /run/secrets/cert.pem
      - source: pki.millegrille
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: pki.redis
        target: key.pem
      - source: passwd.redis
        target: passwd.redis.txt
