services:
  ceduleur:
    image: registry.millegrilles.com/millegrilles/midcompte_python:2026.3.4
    x-millegrilles-certificat:
      roles:
        - ceduleur
      exchanges:
        - 4.secure
        - 3.protege
        - 2.prive
        - 1.public
    command: ["-m", "millegrilles_ceduleur"]
    environment:
      - INSTANCE_ID=${INSTANCE_ID}
      - CA_PATH=/run/secrets/pki.millegrille.cert
      - CERT_PATH=/run/secrets/mgkeycert.pem
      - KEY_PATH=/run/secrets/mgkeycert.pem
      - MQ_HOSTNAME=mq
      - MQ_PORT=${MQ_PORT}
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
    configs:
      - source: mgca
        target: /run/secrets/pki.millegrille.cert
    secrets:
      - source: ceduleur
        target: mgkeycert.pem
    networks:
      - app_net
    depends_on:
      - redis
      - mq
      - mongo
      - midcompte

configs:
  mgca:
    file: ${MILLEGRILLES_ROOT}/etc/millegrille.pem

secrets:
  ceduleur:
    file: ${MILLEGRILLES_ROOT}/secrets/ceduleur.pem
