services:
  midcompte:
    image: registry.millegrilles.com/millegrilles/midcompte_python:2026.4.28
    x-millegrilles-certificat:
      roles:
        - midcompte
      dns:
        localhost: true
        hostnames:
          - midcompte
        domain: true
      passwords:
        - mqadmin
    environment:
      - WEB_PORT=2444
      - KEY_PEM=/run/secrets/key_cert.pem
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 1000
    configs:
      - source: mgca
        target: /run/secrets/pki.millegrille.cert
    secrets:
      - source: midcompte
        target: key_cert.pem
      - source: passwd_mongo
        target: passwd.mongo.txt
      - source: passwd_mqadmin
        target: passwd.mqadmin.txt
    hostname: midcompte
    networks:
      - app_net
    depends_on:
      - redis
      - mq
      - mongo

configs:
  mgca:
    file: ${MILLEGRILLES_ROOT}/etc/millegrille.pem

secrets:
  midcompte:
    file: ${MILLEGRILLES_ROOT}/secrets/midcompte.pem
  passwd_mongo:
    file: ${MILLEGRILLES_ROOT}/secrets/mongo.txt
  passwd_mqadmin:
    file: ${MILLEGRILLES_ROOT}/secrets/mqadmin.txt

networks:
  app_net:
    name: ${INSTANCE_NAME}_net
    external: true
