services:
  mq:
    image: registry.millegrilles.com/millegrilles/rabbitmq:4.2.5-management-alpine.master.13
    x-millegrilles-certificat:
      roles:
        - mq
      dns:
        localhost: true
        hostnames:
          - mq
        domain: true
      split: true
    user: "${CONTAINER_UID}:${CONTAINER_GID}"
    hostname: mq
    environment:
      - MG_KEY=/run/secrets/key.pem
      - WEB_KEY=/run/secrets/key.pem
      - CONFIG_FILE=/opt/rabbitmq/dist/config/rabbitmq.config
      - NODENAME=rabbit@mq
    volumes:
      - ${MILLEGRILLES_ROOT}/var/mq:/var/lib/rabbitmq
    networks:
      - app_net
    ports:
      - "5673:5673"
      # - "8443:8443"
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 2100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
    configs:
      - source: mgca
        target: /opt/rabbitmq/dist/certs/calist.cert.pem
      - source: mqcert
        target: /opt/rabbitmq/dist/certs/cert.pem
      - source: mqcert
        target: /opt/rabbitmq/dist/certs/webcert.pem
      - source: mqkey
        target: /opt/rabbitmq/dist/keys/key.pem
      - source: mqkey
        target: /opt/rabbitmq/dist/keys/webkey.pem
    # A faire -> fix secrets, env params ne fonctionnent pas. Changer rabbitmq.config pour pointer vers /run/secrets pour cles
    secrets:
      - source: mqkey
        target: key.pem
      - source: mqkey
        target: webkey.pem

secrets:
  mqcert:
    file: ${MILLEGRILLES_ROOT}/secrets/mq.cert.pem
  mqkey:
    file: ${MILLEGRILLES_ROOT}/secrets/mq.key.pem
  mgca:
    file: ${MILLEGRILLES_ROOT}/etc/millegrille.pem
