services:
  mq:
    image: registry.millegrilles.com:5000/millegrilles/rabbitmq:4.2.5-management-alpine.master.13
    x-millegrilles-certificat:
      roles:
        - mq
      dns:
        localhost: true
        hostnames:
          - mq
        domain: true
      split: true
    hostname: mq
    environment:
      - MG_KEY=/run/secrets/key.pem
      - WEB_KEY=/run/secrets/webkey.pem
      - CONFIG_FILE=/opt/rabbitmq/dist/config/rabbitmq.config
      - NODENAME=rabbit@mq
    volumes:
      - ./var/mq:/var/lib/rabbitmq
    networks:
      - app_net
    deploy:
      placement:
        constraints:
          - node.labels.millegrilles.mq == true
      resources:
        limits:
          cpus: '3.0'
          memory: 2100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
    configs:
      - source: mgca
        target: /opt/rabbitmq/dist/certs/calist.cert.pem
      - source: mq
        target: /opt/rabbitmq/dist/certs/cert.pem
      - source: web
        target: /opt/rabbitmq/dist/certs/webcert.pem
    secrets:
      - source: mq
        target: key.pem
      - source: web
        target: webkey.pem

configs:
  web:
    file: ${MILLEGRILLES_ROOT}/secrets/web.cert.pem
  mq:
    file: ${MILLEGRILLES_ROOT}/secrets/mq.cert.pem
  mgca:
    file: ${MILLEGRILLES_ROOT}/etc/millegrille.pem

secrets:
  web:
    file: ${MILLEGRILLES_ROOT}/secrets/web.key.pem
  mq:
    file: ${MILLEGRILLES_ROOT}/secrets/mq.key.pem
