services:
  nginx:
    image: registry.millegrilles.com/millegrilles/nginx:1.31.0.null.2
    x-millegrilles-certificat:
      roles:
        -  nginx
      dns:
        localhost: true
        hostnames:
          - nginx
        domain: true
      split: true
    volumes:
      - ${MILLEGRILLES_ROOT}/etc/nginx:/etc/nginx/conf.d/modules:ro
      - ${MILLEGRILLES_ROOT}/var/nginx/html:/usr/share/nginx/html:ro
    networks:
      - app_net
    ports:
      - "443:443"
      - "444:444"
      - "80:80"
      - "1443:1443"
      - "1444:1444"
      - "1445:1445"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 30M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
    configs:
      - source: pki_web
        target: /run/secrets/webcert.pem
      - source: pki_nginx
        target: /run/secrets/nginx.cert.pem
      - source: pki_millegrille
        target: /usr/share/nginx/files/certs/millegrille.cert.pem
    secrets:
      - source: pki_web
        target: webkey.pem
      - source: pki_nginx
        target: nginx.key.pem

configs:
  pki_web:
    file: ${MILLEGRILLES_ROOT}/etc/secrets/web.cert
  pki_nginx:
    file: ${MILLEGRILLES_ROOT}/etc/secrets/nginx.cert
  pki_millegrille:
    file: ${MILLEGRILLES_ROOT}/etc/millegrilles.pem

secrets:
  pki_web:
    file: ${MILLEGRILLES_ROOT}/etc/secrets/web.key
  pki_nginx:
    file: ${MILLEGRILLES_ROOT}/etc/secrets/nginx.key
