include:
  - path: ../include/app_net.yml
    project_directory: .

name: ${INSTANCE_NAME}

services:
  nginx:
    image: registry.millegrilles.com/millegrilles/nginx:1.31.null.4
    x-millegrilles-certificat:
      roles:
        - nginx
      dns:
        localhost: true
        hostnames:
          - nginx
        domain: true
      split: true
    volumes:
      - ${MILLEGRILLES_ROOT}/etc/nginx:/etc/nginx/conf.d/modules:ro
      - ${MILLEGRILLES_ROOT}/var/nginx/html:/usr/share/nginx/html:ro
    networks:
      - app_net
    ports:
      - "443:443"
      - "444:444"
      - "80:80"
      - "1443:1443"
      - "1444:1444"
      - "1445:1445"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 30M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
    secrets:
      - source: webcert
        target: /run/secrets/webcert.pem
      - source: mgcert
        target: /run/secrets/nginx.cert.pem
      - source: mgca
        target: /usr/share/nginx/files/certs/millegrille.cert.pem
      - source: webkey
        target: webkey.pem
      - source: mgkey
        target: nginx.key.pem

secrets:
  webcert:
    file: ${MILLEGRILLES_ROOT}/secrets/web.cert.pem
  mgcert:
    file: ${MILLEGRILLES_ROOT}/secrets/nginx.cert.pem
  mgca:
    file: ${MILLEGRILLES_ROOT}/etc/millegrille.pem
  webkey:
    file: ${MILLEGRILLES_ROOT}/secrets/web.key.pem
  mgkey:
    file: ${MILLEGRILLES_ROOT}/secrets/nginx.key.pem
