services:
  protected_webapi:
    image: registry.millegrilles.com/millegrilles/web_python:2026.3.4
    x-millegrilles-certificat:
      roles:
        - protected_webapi
        - private_webapi
      exchanges:
        - 3.protege
        - 2.prive
        - 1.public
      dns:
        localhost: true
        hostnames:
          - protected-webapi
        domain: true
      passwords:
        - protectedwebapisession
    command: ["-m", "millegrilles_web"]
    environment:
      - MQ_HOSTNAME=${MQ_HOST}
      - MQ_PORT=${MQ_PORT}
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD_PATH=/run/secrets/passwd.redis.txt
      - CERT_PATH=/run/secrets/key.pem
      - KEY_PATH=/run/secrets/key.pem
      - CA_PATH=/run/secrets/millegrille.cert.pem
      - WEB_PORT=1443
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 150M
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 1000
    configs:
      - source: mgca
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: webapi
        target: cert.pem
      - source: webapi
        target: webcert.pem
      - source: webapi
        target: key.pem
      - source: webapi
        target: webkey.pem
      - source: passwd_redis
        target: passwd.redis.txt
    hostname: protected-webapi
    networks:
      - app_net

configs:
  mgca:
    file: ${MILLEGRILLES_ROOT}/etc/millegrille.pem

secrets:
  webapi:
    file: ${MILLEGRILLES_ROOT}/secrets/protected_webapi.pem
  passwd_redis:
    file: ${MILLEGRILLES_ROOT}/secrets/redis.txt
