services:
  redis:
    image: registry.millegrilles.com/millegrilles/redis:8.6.2-alpine.master.9
    x-millegrilles-certificat:
      roles:
        - redis
      dns:
        localhost: true
        hostnames:
          - redis
        domain: true
      split: true
      passwords:
        - redis
    hostname: redis
    volumes:
      # Utilisation volume a cause de la protection des fichiers ACL (dans l'image redis, peut pas changer UID)
      - redis-data:/data
    networks:
      - app_net
    # ports:
    #   - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1000
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli --user client_nodejs -a $(cat /run/secrets/passwd.redis.txt) --tls --cacert /run/secrets/millegrille.cert.pem --cert /run/secrets/cert.pem --key /run/secrets/key.pem ping | grep -q PONG" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    configs:
      - source: redis
        target: /run/secrets/cert.pem
      - source: mgca
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: redis
        target: key.pem
      - source: passwd_redis
        target: passwd.redis.txt

configs:
  redis:
    file: ${MILLEGRILLES_ROOT}/secrets/redis.cert.pem
  mgca:
    file: ${MILLEGRILLES_ROOT}/etc/millegrille.pem

secrets:
  redis:
    file: ${MILLEGRILLES_ROOT}/secrets/redis.key.pem
  passwd_redis:
    file: ${MILLEGRILLES_ROOT}/secrets/redis.txt

volumes:
  redis-data:
    name: ${INSTANCE_NAME}-redis-data

networks:
  app_net:
    name: ${INSTANCE_NAME}_net
    external: true
