services:
  webauth:
    image: registry.millegrilles.com/millegrilles/webauth_python:2026.3.3
    x-millegrilles-certificat:
      roles:
        - webauth
      exchanges:
        - 1.public
      dns:
        localhost: true
        hostnames:
          - webauth
        domain: true
    environment:
      - MQ_HOSTNAME=${MQ_HOST}
      - MQ_PORT=${MQ_PORT}
      - REDIS_PORT=6379
      - REDIS_PASSWORD_PATH=/run/secrets/redis.txt
      - CERT_PATH=/run/secrets/key.pem
      - KEY_PATH=/run/secrets/key.pem
      - CA_PATH=/run/secrets/millegrille.cert.pem
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 100
    configs:
      - source: mgca
        target: /run/secrets/millegrille.cert.pem
    secrets:
      - source: webauth
        target: key.pem
      - source: passwd_redis
        target: redis.txt
    networks:
      - app_net

configs:
  mgca:
    file: ${MILLEGRILLES_ROOT}/etc/millegrille.pem

secrets:
  webauth:
    file: ${MILLEGRILLES_ROOT}/secrets/webauth.pem
  passwd_redis:
    file: ${MILLEGRILLES_ROOT}/secrets/redis.txt
