INSTANCE_CONFIG_PATH = 'INST_CONFIG_PATH'
INSTANCE_SECRETS_PATH = 'INST_SECRETS_PATH'
INSTANCE_SECRETS_PARTAGES_PATH = 'INST_SECRETS_PARTAGES_PATH'
INSTANCE_NGINX_PATH = 'INST_NGINX_PATH'

WEB_APP_PATH = 'WEB_APP_PATH'

ENV_WEB_CERT_PEM = 'WEB_CERT_PEM'
ENV_WEB_KEY_PEM = 'WEB_KEY_PEM'
ENV_WEB_PORT = 'WEB_PORT'

CONFIG_INSTANCE_ID = 'instance.id'
CONFIG_INSTANCE_SECURITE = 'instance.securite'
CONFIG_INSTANCE_IDMG = 'instance.idmg'

CERTISSUER_PATH = 'CERTISSUER_PATH'
