INSTANCE_CONFIG_PATH = 'INST_CONFIG_PATH'
INSTANCE_SECRETS_PATH = 'INST_SECRETS_PATH'
INSTANCE_SECRETS_PARTAGES_PATH = 'INST_SECRETS_PARTAGES_PATH'
INSTANCE_NGINX_PATH = 'INST_NGINX_PATH'

WEB_APP_PATH = 'WEB_APP_PATH'
